### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by lipkau** [PSJira/PSJira#104]
I would suggest we create a Gitter chat or, preferably, **a Slack** domain for PSJira.
This would allow for easier discussions, etc.
Other modules (DBAtools) also use this approach.

If I am not alone in thinking this could be a good idea, I will arrange for it.

**Comment by replicaJunction** [comment]
Slack sounds good to me!

**Comment by lipkau** [comment]
https://psjira.slack.com/shared_invite/MTg2MzM0MTA4Njg5LTE0OTU1NTYwNTAtODg2OTlmN2RlMw
