### ISSUE TITLE
Alert about CAPTCHAs when authenticating

### ISSUE THREAD

**Issue by lipkau** [PSJira/PSJira#107]
#87 mentioned that logins might failed due to CAPTCHAs.

[Jira Rest Api Example: Basic Authentication](https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-example-basic-authentication) describes how CAPTCHAs work.

We should implement a check for the header `X-Seraph-LoginReason = "AUTHENTICATION_DENIED"` and if present, give the user feedback in the likes of "Jira requires additional information for your login. Please use the Jira site to authenticate and then try again"

**Comment by lipkau** [comment]
I was able to reproduce the problem.

I used incorrect credentials 30 times in order to trigger the captcha (which #107 is catching fine).
However, I am unable to get the header with the captcha information to reset, as when I login on the website I do not get a captcha.

I have asked the Atlassian support for help: https://getsupport.atlassian.com/servicedesk/customer/portal/23/JST-288856

**Comment by 123dev** [comment]
Thanks Oliver.

So you suspect that captcha is kicking in?
I made a call using Postman,
I got
`{
  "errorMessages": [
    "Login failed"
  ],
  "errors": {}
}`

But I don't see the header: `X-Seraph-LoginReason`
![image](https://cloud.githubusercontent.com/assets/13109154/26413767/fe47e56c-407a-11e7-9aaa-ba242573b7bb.png)

PS: the JST-288856 seems to be private, can't see or subscribe.
Thanks

**Comment by lipkau** [comment]
hm. so maybe it is unrelated.
because I get the header:
http://img02.imgland.net/azz0HD7.png
with body
```json
{
  "errorMessages": [
    "Login failed"
  ],
  "errors": {}
}
```

**Comment by 123dev** [comment]
Perhaps, either way seems to be a Jira issue.
And one way to workaround it is to use Basic Auth or oAuth to get the cookie.

or document that username should be used for session cookie.

When I replace my email with my username.
I get
```
{
  "session": {
    "name": "cloud.session.token",
    "value": "redacted..."
  }
}
```

![image](https://cloud.githubusercontent.com/assets/13109154/26414368/fe60cf26-407c-11e7-9eab-711efeb3ed7d.png)

**Comment by lipkau** [comment]
So definitely different problems.
I get the same 401 when I use the username instead of the password

**Comment by JohnLBevan** [comment]
FYI: It looks like this is a confirmed bug with the Cloud offerring: https://jira.atlassian.com/browse/JRACLOUD-46830?jql=text%20~%20%22401%20rest%22

**Comment by JohnLBevan** [comment]
Has anyone ever seen the captcha?
After getting the error I navigated to various URLs in the browser to see if I could view & complete the captcha; hoping that after this I could return to using the script.
If there is a page where the captcha's displayed, for interactive sessions, we could use something like this:
https://gist.github.com/JohnLBevan/650f1d96d52ecf4dfcc1ed277bbd3744/

**Comment by lipkau** [comment]
This must be tested with #116 .

**Comment by lipkau** [comment]
@JohnLBevan : on my non-cloud instance I have been able to get them. But no url to explicitly access them. It's always after trying to enter your creds that it refreshed to the same page but with captcha
