### ISSUE TITLE
Can't use a Secure String as credentials with PSJira

### ISSUE THREAD

**Issue by JoeJe1993** [PSJira/PSJira#119]
We have an unmanned account we'd like to create tickets from, however, this involves us having to store the credentials in the script. To mitigate against the risk of storing the credentials in plain-text, I've tried storing the username and password as a secure string (There's a ConvertFrom-SecureString at the end of $SecureString). 

The following occurs when trying to execute with the secure string:

![image](https://cloud.githubusercontent.com/assets/29064065/26728027/c35e1dea-47a0-11e7-8afd-201cb2828bf4.png)

**Comment by lipkau** [comment]
`PSCredentials` takes 2 arguments. The first being the _username_.
Here is an example: https://blogs.msdn.microsoft.com/koteshb/2010/02/12/powershell-how-to-create-a-pscredential-object/

But if your goal is only to store the credentials securely on the local computer, I would recommended storing it in the _Windows Credential Store_ with _[BetterCredentials](https://github.com/Jaykul/BetterCredentials)

**Comment by lipkau** [comment]
@JoeJe1993 : please close the issue once it is resolved
