### ISSUE TITLE
Config.xml file is sometimes "locked" in Azure Automation runbooks using the PSJira module

### ISSUE THREAD

**Issue by APraestegaard** [PSJira/PSJira#124]
A handful runbooks where some of these run in a hybrid worker context uses this module in Azure Automation. Once in a while (mostly not) the module loading fails with the exception (the same error is presented twice in the Azure portal exception tile):
> Exception calling "Save" with "1" argument(s): "The process cannot access the file 'C:\Modules\User\PSJira\config.xml' because it is being used by another process." (Exception calling "Save" with "1" argument(s): "The process cannot access the file 'C:\Modules\User\PSJira\config.xml' because it is being used by another process." (The process cannot access the file 'C:\Modules\User\PSJira\config.xml' because it is being used by another process.))

### Possible Solution
How important is this config file? (in my environment it only contains only one line with the jira-web-address)

### Context
When the issue is there it's a huge problem

### Your Environment
PSJira module version: 1.2.5.160

Hybrid runbook worker is in a 2016 server but the problem is also on 2012  (when not in a Hybrid Runbook Worker I can't tell the specific environment)
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.14393.0                                                                             
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.14393.0                                                                            
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1

**Comment by lipkau** [comment]
Hi @APraestegaard 
When does this error occur? Only when you execute the `Set-JiraConfigServer` command?

I am trying to identify if you have too many workers writing to the file at the same time or if it is an other kind of access to the file

**Comment by APraestegaard** [comment]
Hi @lipkau - Thank you for getting back on this.

> When does this error occur? Only when you execute the Set-JiraConfigServer command?

I know only of this happening in Set-JiraconfigServer.ps1 when the config file is saved:

```
PositionMessage : At C:\Modules\User\PSJira\Public\Set-JiraConfigServer.ps1:88 char:9

                  +         $xml.Save($ConfigFile)

                  +         ~~~~~~~~~~~~~~~~~~~~~~
```

> I am trying to identify if you have too many workers writing to the file at the same time or if it is an other kind of access to the file
Runbooks are the only process that consumes the file, and the file is locked for writing while used so it makes fine sense. 

I am curious if you know why this config-file-approach is taken, when in reality all it does is hold a global variable?

**Comment by APraestegaard** [comment]
To avoid the problem I am surrounding the Set-JiraConfigServer with the following code:
```
$timeout = 60
$psJiraLoaded = $false
do
{           
    Start-Sleep -Seconds 1
    $timeout--

    try
    {
        #Write-Error -Exception (New-Object -TypeName System.IO.IOException) -ErrorAction Stop
        Set-JiraConfigServer $JiraURL
        $psJiraLoaded = $true
    }
    catch [System.IO.IOException]
    {
        Write-Warning -Message "Jira-module is loaded by a different process ($timeout)"
    }

    if ($timeout -eq 0)
    {
        throw "Timeout trying to load PSJira module"
    }
}
until ($psJiraLoaded)
```

**Comment by lipkau** [comment]
I would have suggested to read the value in the file and only use the set command if the value is incorrect.

I don't know the history of that decision. However some ideas we are working on will enhance the file and the experience around it.
But nothing is keeping us to implemented and additional way to set the variable.
If you won't, I will open an issue to discuss possible approaches

**Comment by lipkau** [comment]
There for I would suggest for this issue to be closed and the new one, with the discussion mentioned above, will continue this.

**Comment by lipkau** [comment]
@APraestegaard can I close this?

**Comment by APraestegaard** [comment]
Sure - do that.
Thanks!
