### ISSUE TITLE
New-JiraIssue Creation with Fields errors

### ISSUE THREAD

**Issue by tylerapplebaum** [PSJira/PSJira#136]
Here are the 2 custom fields I'm attempting to use:

```
ID          : customfield_10103
Searchable  : True
Schema      : @{type=string; custom=com.atlassian.jira.plugin.system.customfieldtypes:textfield; customId=10103}
Name        : Account Name
Custom      : True
Navigable   : True
Orderable   : True
ClauseNames : {Account Name, cf[10103]}

ID          : customfield_10104
Searchable  : True
Schema      : @{type=string; custom=com.atlassian.jira.plugin.system.customfieldtypes:textfield; customId=10104}
Name        : Site Name
Custom      : True
Navigable   : True
Orderable   : True
ClauseNames : {cf[10104], Site Name}
```

Here is the command I'm entering to create a new issue:
```
New-JiraIssue -Project NOC -IssueType Incident -Priority 3 -Summary "Testing - 123" -Description "Test - June 2017" -Fields @{
'customfield_10103' = 'Test' #Account Name
'customfield_10104' = 'Test2' #Site Name
} -Credential mycred
```

Here is the error message I receive:
```
Get-Member : You must specify an object for the Get-Member cmdlet.
At C:\Program Files\WindowsPowerShell\Modules\PSJira\1.2.5.251\Internal\ConvertTo-JiraCreateMetaField.ps1:37 char:32
+ ... eldNames = (Get-Member -InputObject $fields -MemberType '*Property'). ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
    + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand
```

**Comment by lipkau** [comment]
can you please send us the output of 
```posh
$DebugPreference = "continue"
Get-JiraIssueCreateMetadata -Project NOC -IssueType Incident
```

**Comment by tylerapplebaum** [comment]
Output below; username removed.

`PS C:\Users\<username>\Desktop> $DebugPreference = "continue"
Get-JiraIssueCreateMetadata -Project NOC -IssueType Incident -Credential <username>
DEBUG: [Get-JiraIssueCreateMetadata] Reading server from config file
DEBUG: [Get-JiraIssueCreateMetadata] Building URI for REST call based on parameters
DEBUG: [Get-JiraIssueCreateMetadata] Obtaining project ID for project [NOC]
DEBUG: [Get-JiraProject] Reading server from config file
DEBUG: [Get-JiraProject] Processing project [NOC]
DEBUG: [Get-JiraProject] Preparing for blastoff!
DEBUG: [Invoke-JiraMethod] Using HTTP Basic authentication with provided credentials for applebaumt
DEBUG: [Invoke-JiraMethod] Invoking JIRA method Get to URI https://jira.ochin.org/rest/api/latest/project/NOC?expand=projectKeys
DEBUG: [Invoke-JiraMethod] Status code: 200
DEBUG: [Invoke-JiraMethod] Converting body of response from JSON
DEBUG: [Invoke-JiraMethod] Outputting results from JIRA
DEBUG: [Get-JiraProject] Converting to object
DEBUG: [Get-JiraProject] Outputting result
DEBUG: Complete
DEBUG: [Get-JiraIssueCreateMetadata] Obtaining issue type ID for issue type [Incident]
DEBUG: [Get-JiraIssueType] Reading server from config file
DEBUG: [Get-JiraIssueType] Obtaining all issue types from Jira
DEBUG: [Invoke-JiraMethod] Using HTTP Basic authentication with provided credentials for applebaumt
DEBUG: [Invoke-JiraMethod] Invoking JIRA method Get to URI https://jira.ochin.org/rest/api/latest/issuetype
DEBUG: [Invoke-JiraMethod] Status code: 200
DEBUG: [Invoke-JiraMethod] Converting body of response from JSON
DEBUG: [Invoke-JiraMethod] Outputting results from JIRA
DEBUG: [ConvertTo-JiraIssueType] Complete
DEBUG: [Get-JiraIssueType] Processing issue type [Incident]
DEBUG: [Get-JiraIssueType] Searching for issue type (name=[Incident])
DEBUG: [Get-JiraIssueType] Found results; outputting
DEBUG: Complete
DEBUG: [Get-JiraIssueCreateMetadata] Preparing for blastoff!
DEBUG: [Invoke-JiraMethod] Using HTTP Basic authentication with provided credentials for applebaumt
DEBUG: [Invoke-JiraMethod] Invoking JIRA method Get to URI https://jira.ochin.org/rest/api/latest/issue/createmeta?projectIds=10100&issuetypeIds=10000&expand=projects.issuetypes.fields
DEBUG: [Invoke-JiraMethod] Status code: 200
DEBUG: [Invoke-JiraMethod] Converting body of response from JSON
DEBUG: [Invoke-JiraMethod] Outputting results from JIRA
DEBUG: [Get-JiraIssueCreateMetadata] Identified project key: [NOC]
DEBUG: [Get-JiraIssueCreateMetadata] Converting results to custom object
DEBUG: [ConvertTo-JiraCreateMetaField] Processing object: '@{expand=projects; projects=}'
Get-Member : You must specify an object for the Get-Member cmdlet.
At C:\Program Files\WindowsPowerShell\Modules\PSJira\1.2.5.251\Internal\ConvertTo-JiraCreateMetaField.ps1:37 char:32
+ ... eldNames = (Get-Member -InputObject $fields -MemberType '*Property'). ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
    + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand
 
DEBUG: Outputting results`

**Comment by tylerapplebaum** [comment]
Ah ok, well looks like Incident is no longer a valid issue type for this project. I changed it to 'problem' and no longer receive this error. 

I do receive another error where one of the required custom fields expects the value to be in an array, but I will figure that out.

**Comment by tylerapplebaum** [comment]
Maybe a quick follow up if I can... How would I go about getting these values out of this field and selecting one?

![image](https://user-images.githubusercontent.com/8419153/27236891-a5649e00-527b-11e7-9ab1-63fafdf90dfb.png)

**Comment by tylerapplebaum** [comment]
Never mind... got that too. Boy you have some good documentation 👍 

I had to convert the 'Requesting organization' field to a hashtable array like you described.

```
'customfield_10401' = @(@{
        value = 'LN-570 BLAH BLAH'
    })
```

**Comment by lipkau** [comment]
glad you found everything you needed.
Was it on [readthedocs](https://psjira.readthedocs.io) that you found the information?

**Comment by tylerapplebaum** [comment]
Yes it was, the Working With Fields page specifically.

**Comment by lipkau** [comment]
nice!
good to know.
That's motivation to document the new feature in a similar way
