### ISSUE TITLE
Add Support for Fields parameter on Invoke-JiraIssueTransition

### ISSUE THREAD

**Issue by padgers** [PSJira/PSJira#38]
Hi @replicaJunction 

Really great to see the recent changes added to PSJira. 

I've had a few instances recently where I needed to perform additional field changes along with an issue transition. Using a separate Set-JiraIssue wasn't an option due to our JIRA configuration (permissions). Changing fields along with a transition is supported in the [JIRA API](https://docs.atlassian.com/jira/REST/cloud/#api/2/issue-doTransition) so I thought I'd have a crack at adding this functionality. Essentially I have copied and adapted the field parameter functionality from Set-JiraIssue.

I have also given my best shot at updating the pester tests for this new parameter. As above I have copied and adapted the fields parameter test from Set-JiraIssue.Tests. The new test passes, but I'm still getting my head around pester testing in general so would be interested to know if you think this new test is adequate.

Let me know if you're happy with these changes and I'll submit a pull do the Dev branch.

[Invoke-JiraIssueTransition.txt](https://github.com/replicaJunction/PSJira/files/430955/Invoke-JiraIssueTransition.txt)
[Invoke-JiraIssueTransition.Tests.txt](https://github.com/replicaJunction/PSJira/files/430956/Invoke-JiraIssueTransition.Tests.txt)

Thanks
Padgers

**Comment by replicaJunction** [comment]
Looks awesome! This is a great example of why I love open-source. :D

Out of random curiosity, have you already tested this in your environment? Someday, I'd like to design an integration test script for the module that actually manipulates issues against my test instance of JIRA, but that will probably take some time.

~replica

**Comment by padgers** [comment]
Really happy to be able to add something to this project!

Yes, I've tested with some custom fields we use. However, when repeating these tests it occurred to me that to fully align the features with the Set-JiraIssue function, it also may be a good idea to add assignee and comment parameters as neither would work using the new fields parameter. That's something I'm prepared to take a look at also. I guess the next step depends if you're happy for me to make this particular pull or would rather wait until all the parameters are added (assuming you agree with their addition) and then pull? 
Padgers

**Comment by replicaJunction** [comment]
Yeah, I could see both assignee and comment being useful in a transition as well. I'd say feel free to go ahead and submit a PR for these changes, and when the Assignee and Comment params are ready, we can merge those in at that point.

**Comment by padgers** [comment]
It's been a long time coming (sorry for that) but I just made the PR for _all_ these changes discussed. Really interested for thoughts/feedback. The new tests I've written do pass, but as before I'd like to know if they're adequate.
