### ISSUE TITLE
Pester error: RuntimeException: Module 'PSJira' is not a Script module.

### ISSUE THREAD

**Issue by chrisdarth** [PSJira/PSJira#46]
Hello! Thanks for the great work you've done here!

When running Invoke-Pester for the module, the result is: _Passed: 62 Failed: 44 Skipped: 0 Pending: 0 Inconclusive: 0_

Error output:

```
 [-] Error occurred in test script 'C:\Projects\PSJira\PSJira\Internal\ConvertTo-JiraComment.Tests.ps1' 45ms
   RuntimeException: Module 'PSJira' is not a Script module.  Detected modules of the following types: ''
   at Get-ScriptModule, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Functions\InModuleScope.ps1: line 128
 [-] Error occurred in test script 'C:\Projects\PSJira\PSJira\Internal\ConvertTo-JiraCreateMetaField.Tests.ps1' 45ms
   RuntimeException: Module 'PSJira' is not a Script module.  Detected modules of the following types: ''
   at Get-ScriptModule, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Functions\InModuleScope.ps1: line 128
```

The issue is that the module has not been loaded. If I run `Import-Module .\PSJira\PSJira.psm1` then run the Pester tests, it succeeds. 

Suggesting tests to include `Import-Module`. A workaround is to manually ensure the module is loaded, but if you forget to reload the module, you'll be testing an out-of-date module.

Best,
CD

**Comment by replicaJunction** [comment]
Hey chrisdarth, thanks for the bug report! I definitely agree with you on this.

I'm trying to figure out a way to run Import-Module -Force once while testing, but not for every single script tested (depending on the machine, sometimes that Import-Module -Force can take a while). I might end up building a "test script" that acts as a wrapper for Invoke-Pester that includes some error checking.

**Comment by replicaJunction** [comment]
This issue should be resolved with the recent changes to the tests in d916869! The Shared.ps1 file now handles the module import.
