### ISSUE TITLE
Close issue powershell

### ISSUE THREAD

**Issue by yannickIT** [PSJira/PSJira#91]
Hello,

I need your help

I want to close this ticket using transition with powershell for closing.

The transition is working, but i need to set parameters to my issue. This one : 

```powershell
PS C:\Users\adm-task\Documents> Get-JiraIssue IPE-952 | Select-Object -ExpandProperty resolution

self                             id                               description                      name                            
----                             --                               -----------                      ----                            
https://jira.stva.com/rest/ap... 10201                            Idée ou demande d'évolution r... Approuved
```    

![image](https://cloud.githubusercontent.com/assets/28387595/25698236/5c5201b4-30be-11e7-88a7-a7f3d5033648.png)
![image](https://cloud.githubusercontent.com/assets/28387595/25698392/f0bfd8ee-30be-11e7-8816-d4c13cbd01a7.png)

Thanks for your help

**Comment by lipkau** [comment]
`Invoke-JiraIssueTransition` should support the parameter: `-Comment` and `-Fields`.

https://docs.atlassian.com/jira/REST/cloud/#api/2/issue-doTransition

**Comment by lipkau** [comment]
duplicates #38
